Ruby/config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'

  resources :users, only: [:new, :create]

  resources :posts, only: [:destroy, :edit, :update]
  get 'posts/:id/new' => 'posts#topic_posts', as: 'new_post'
  post 'posts/:id/new' => 'posts#create'
  get 'topic_posts/:id' => 'posts#topic_posts', as: 'topic_posts'

  resources :topics, only: [:destroy, :edit, :update]
  get 'topics/:id/new' => 'topics#new', as: 'new_topic'
  post 'topics/:id/new' => 'topics#create'
  get 'forum_topics/:id' => 'topics#forum_topics', as: 'forum_topics'

  resources :forums, only: [:new, :edit, :update, :create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy, :index]

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

Ruby/app/views/layouts/application.html.haml
!!!
%html{ lang: "pl" }
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Forum
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag :defaults, "nested_form"
    = csrf_meta_tags


  %body
    %div.container
      %div.row
        %nav.navbar.navbar-default{role: 'navigation'}
          %div.navbar-header
            %button.navbar-toggle.collapsed{type: 'button', 'data-toggle' => 'collapse', 'data-target' => '#nav-menu'}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

          %div#nav-menu.collapse.navbar-collapse
            %ul.col-xs-12.nav.navbar-nav
              - if is_active?(root_path)
                %li.active
                  = link_to "Index", root_path
              - else
                %li
                  = link_to "Index", root_path

              - if signed_in?
                %li.navbar-right
                  = link_to logout_path, method: :delete do
                    Wyloguj (
                    = current_user.login
                    )
              - else
                - if is_active?(login_path) || is_active?(sessions_path)
                  %li.active.navbar-right
                    = link_to "Zaloguj", login_path
                - else
                  %li.navbar-right
                    = link_to "Zaloguj", login_path

                - if is_active?(new_user_path)
                  %li.active.navbar-right
                    = link_to "Zarejestruj", new_user_path
                - else
                  %li.navbar-right
                    = link_to "Zarejestruj", new_user_path

      - if notice
        %div.row
          %div{ role: 'alert', class: cookies[:notice_type] ? "alert alert-" + cookies[:notice_type] + " alert-dismissible" : "alert alert-info alert-dismissible" }
            = notice
            %button.close{ 'aria-label' => "Close", 'data-dismiss' => "alert", 'type' => "button" }
              %span{ 'aria-hidden' => "true" }
                ×


      %div.row
        = yield

      %br
      %div.row
        %div.panel.panel-default.text-center
          %div.panel-footer
            %small
              &copy; Damian Giebas 2015 -
              = Time.now.year