Ruby/config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'

  resources :users, only: [:new, :create]

  resources :posts, only: [:destroy, :edit, :update]
  get 'posts/:id/new' => 'posts#topic_posts', as: 'new_post'
  post 'posts/:id/new' => 'posts#create'
  get 'topic_posts/:id' => 'posts#topic_posts', as: 'topic_posts'

  resources :topics, only: [:destroy, :edit, :update]
  get 'topics/:id/new' => 'topics#new', as: 'new_topic'
  post 'topics/:id/new' => 'topics#create'
  get 'forum_topics/:id' => 'topics#forum_topics', as: 'forum_topics'

  resources :forums, only: [:new, :edit, :update, :create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy, :index]

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

Ruby/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic, :inverse_of => :posts
  belongs_to :user

  #validates :topic, presence: true
  validates :user, presence: true

  validates :content, length: { minimum: 10 }

  default_scope -> { order(created_at: :asc) }
end

Ruby/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :edit, :update, :destroy]
  before_action :set_post, only: [:edit, :destroy, :update]
  before_action :set_view_content, only: [:create, :topic_posts]
  before_action :set_view_content2, only: [:edit, :update]

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new content: params[:post][:content], topic_id: params[:id]

    respond_to do |format|
      if @post.save
        format.html { redirect_to topic_posts_path(@post.topic_id), notice: 'Post was successfully created.' }
      else
        format.html { render :topic_posts }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to topic_posts_path(@post.topic_id), notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
  topic_id = @post.topic_id
    @post.destroy
    respond_to do |format|
      format.html { redirect_to topic_posts_path(topic_id), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def topic_posts
    @post = Post.new topic_id: params[:id]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :content, :topic_id)
    end

    def set_view_content
      @posts = Post.where topic_id: params[:id]
      @forum = Topic.find(params[:id]).forum
    end

    def set_view_content2
      @posts = @post.topic.posts
      @forum = @post.topic.forum
    end
end

Ruby/app/views/posts/edit.html.haml
%div#button-panel.col-xs-12
  = link_to "Powrót", forum_topics_path(@forum), class: "btn btn-link pull-right"

%div.col-xs-12
  %div.row
    - if @posts
      %div.table-responsive
        %table.table.table-striped
          %tbody
            - @posts.each do |post|
              %tr
                %td.col-xs-3
                  %div.col-xs-12
                    = post.user.login
                  %div.col-xs-12
                    = post.created_at
                %td.col-xs-8
                  = post.content
                %td.col-xs-1
                  - if  current_user.admin
                    = link_to post, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-link pull-right" do
                      %span.glyphicon.glyphicon-trash
                  - if current_user.admin || current_user.id == post.user_id
                    = link_to edit_post_path(post), class: "btn btn-link pull-right" do
                      %span.glyphicon.glyphicon-edit

%div.col-xs-12.col-sm-6.col-sm-push-3
  %div.row
    = bootstrap_nested_form_for @post do |f|
      = f.text_area :content, placeholder: "Wiadomość", label: "Wiadomość"

      = f.submit 'Wyślij post', class: "btn btn-primary"

%div.col-xs-12
  = link_to "Do góry", "#button-panel", class: "btn btn-link pull-right"

Ruby/app/views/posts/topic_posts.html.haml
%div#button-panel.col-xs-12
  = link_to "Powrót", forum_topics_path(@forum), class: "btn btn-link pull-right"

%div.col-xs-12
  %div.row
    - if @posts
      %div.table-responsive
        %table.table.table-striped
          %tbody
            - @posts.each do |post|
              %tr
                %td.col-xs-3
                  %div.col-xs-12
                    = post.user.login
                  %div.col-xs-12
                    = post.created_at
                %td.col-xs-8
                  = post.content
                %td.col-xs-1
                  - if  current_user.admin
                    = link_to post, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-link pull-right" do
                      %span.glyphicon.glyphicon-trash
                  - if current_user.admin || current_user.id == post.user_id
                    = link_to edit_post_path(post), class: "btn btn-link pull-right" do
                      %span.glyphicon.glyphicon-edit

%div.col-xs-12.col-sm-6.col-sm-push-3
  %div.row
    = bootstrap_nested_form_for @post, url: new_post_path(@post.topic_id) do |f|
      = f.text_area :content, placeholder: "Wiadomość", label: "Wiadomość"

      = f.submit 'Wyślij post', class: "btn btn-primary"

%div.col-xs-12
  = link_to "Do góry", "#button-panel", class: "btn btn-link pull-right"