Ruby/config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'

  resources :users, only: [:new, :create]

  resources :posts, only: [:destroy, :edit, :update]
  get 'posts/:id/new' => 'posts#topic_posts', as: 'new_post'
  post 'posts/:id/new' => 'posts#create'
  get 'topic_posts/:id' => 'posts#topic_posts', as: 'topic_posts'

  resources :topics, only: [:destroy, :edit, :update]
  get 'topics/:id/new' => 'topics#new', as: 'new_topic'
  post 'topics/:id/new' => 'topics#create'
  get 'forum_topics/:id' => 'topics#forum_topics', as: 'forum_topics'

  resources :forums, only: [:new, :edit, :update, :create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy, :index]

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

Ruby/app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :forum, presence: true
  validates :user, presence: true

  validates :name, length: { minimum: 4, maximum: 64 }

  default_scope -> { order(created_at: :desc) }

  accepts_nested_attributes_for :posts
end

Ruby/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_topic, only: [:edit, :update, :destroy]

  def new
    @topic = Topic.new forum_id: params[:id]
    @topic.posts.build
  end

  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new name: params[:topic][:name], forum_id: params[:id], user_id: current_user.id
    @topic.posts.new content: params[:topic][:posts_attributes]["0"][:content], user_id: current_user.id

    @topic.transaction do
      respond_to do |format|
        if @topic.save
          format.html { redirect_to forum_topics_path(params[:id]), notice: 'Topic was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      topic_params[:user_id] = current_user.id
      if @topic.update(topic_params)
        format.html { redirect_to forum_topics_path(@topic.forum_id), notice: 'Topic was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    forum_id = @topic.forum_id
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to forum_topics_path(forum_id), notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def forum_topics
    @topic_list = Topic.where forum_id: params[:id]
    @forum = Forum.find(params[:id])
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, [:content])
    end
end

Ruby/app/views/topics/_form_create.html.haml
%div.col-xs-12.col-sm-6.col-sm-push-3
  = bootstrap_nested_form_for @topic, url: new_topic_path(@topic.forum) do |f|
    = f.text_field :name, placeholder: "Nazwa", label: "Nazwa"
    = f.fields_for :posts do |p|
      = p.text_area :content, placeholder: "Wiadomość", label: "Wiadomość"

    = f.submit 'Stwórz temat', class: "btn btn-primary"
    = link_to 'Anuluj', forum_topics_path(@topic.forum), class: "btn btn-default"

Ruby/app/views/topics/_form_edit.html.haml
%div.col-xs-12.col-sm-6.col-sm-push-3
  = bootstrap_form_for @topic do |f|
    = f.text_field :name, placeholder: "Nazwa", label: "Nazwa"

    = f.submit 'Stwórz temat', class: "btn btn-primary"
    = link_to 'Anuluj', forum_topics_path(@topic.forum), class: "btn btn-default"

Ruby/app/views/topics/edit.html.haml
= render 'form_edit'

Ruby/app/views/topics/forum_topics.html.haml
%div.panel.panel-default
  %div.panel-heading
    %form.form.form-horizontal{ action: '#', onsubmit: 'return false;' }
      %label.control-label.damian-padding-bottom
        = @forum.name

      = link_to "Nowy temat", new_topic_path(@forum), class: "btn btn-default visible-md visible-lg pull-right"
      = link_to "Nowy temat", new_topic_path(@forum), class: "btn btn-default btn-sm btn-block visible-xs visible-sm"

  %div.panel-body
    %div.table-responsive
      %table.table.table-striped
        %tbody
          - @topic_list.each do |topic|
            %tr
              %td
                = link_to topic.name, topic_posts_path(topic), class: "btn btn-link"
                %span.label.label-default.pull-right{ style: 'margin-top: 9px;' }
                  = topic.user.login
                  = topic.created_at.strftime('%d %B %Y %H-%M-%S')
              - if current_user.admin
                %td.col-xs-2
                  = link_to topic, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-link pull-right" do
                    %span.glyphicon.glyphicon-trash
                  = link_to edit_topic_path(topic), class:"btn btn-link pull-right" do
                    %span.glyphicon.glyphicon-edit

Ruby/app/views/topics/new.html.haml
= render 'form_create'