Ruby/config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'

  resources :users, only: [:new, :create]

  resources :posts, only: [:destroy, :edit, :update]
  get 'posts/:id/new' => 'posts#topic_posts', as: 'new_post'
  post 'posts/:id/new' => 'posts#create'
  get 'topic_posts/:id' => 'posts#topic_posts', as: 'topic_posts'

  resources :topics, only: [:destroy, :edit, :update]
  get 'topics/:id/new' => 'topics#new', as: 'new_topic'
  post 'topics/:id/new' => 'topics#create'
  get 'forum_topics/:id' => 'topics#forum_topics', as: 'forum_topics'

  resources :forums, only: [:new, :edit, :update, :create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy, :index]

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

Ruby/app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics, dependent: :restrict_with_exception

  validates :order_nr, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true, length: { minimum: 4, maximum: 64 }
  validates :comment, presence: true, length: { minimum: 4, maximum: 64 }

  default_scope -> { order(order_nr: :asc) }

  validates_uniqueness_of :order_nr
  validates_uniqueness_of :name
end

Ruby/app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :signed_in_user, only: [:new, :edit, :update, :destroy]
  before_action :has_admin_permission, only: [:new, :create, :edit, :update, :destroy]

  expose :forums
  expose :forum, attributes: :forum_params

  # POST /forums
  # POST /forums.json
  def create
    respond_to do |format|
      if forum.save
        format.html { redirect_to root_path, notice: 'Forum was successfully created.' }
        format.json { render :index, status: :created, location: forum }
      else
        format.html { render :new }
        format.json { render json: forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if forum.save
        format.html { redirect_to root_path, notice: 'Forum was successfully updated.' }
        format.json { render :index, status: :ok, location: forum }
      else
        format.html { render :edit }
        format.json { render json: forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  rescue ActiveRecord::DeleteRestrictionError
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum canot be destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :comment, :order_nr)
    end
end

Ruby/app/views/forums/_form.html.haml
%div.col-xs-12.col-sm-6.col-sm-push-3
  = bootstrap_form_for forum do |f|
    = f.text_field :name, placeholder: "Nazwa", label: "Nazwa"

    = f.text_field :comment, placeholder: "Opis", label: "Opis"

    = f.number_field :order_nr, placeholder: "Liczba porządkowa", label: "Liczba porządkowa"

    = f.submit 'Zapisz', class: "btn btn-primary"
    = link_to 'Na główną', root_path, class: "btn btn-default"

Ruby/app/views/forums/edit.html.haml
= render 'form'

Ruby/app/views/forums/index.html.haml
- forums.each do |forum|
  %div.panel.panel-default
    %div.panel-heading
      %div.row
        %div.col-xs-9
          = link_to forum_topics_path(forum), class: "btn btn-link" do
            %div.lead= forum.name

        - if current_user && current_user.admin
          %div.col-xs-3.pull-right
            = link_to forum, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-link pull-right", alt:"Delete" do
              %span.glyphicon.glyphicon-trash
            = link_to edit_forum_path(forum), class:"btn btn-link pull-right", alt:"Edit" do
              %span.glyphicon.glyphicon-edit

    %div.panel-body
      %small
        = forum.comment

- if current_user && current_user.admin
  %div.col-xs-12
    = link_to 'Stwórz forum', new_forum_path, class: "btn btn-link"

Ruby/app/views/forums/new.html.haml
= render 'form'